### PR TITLE
Updated health check

### LINKED ISSUE #40: [Bug] The health check not pass if WOLWEBVDIR set
```dockerfile
HEALTHCHECK --interval=5s --timeout=3s \
    CMD curl --silent --show-error --fail http://localhost:${WOLWEBPORT}/wolweb/health || exit 1
```

The health check URL should be `http://localhost:${WOLWEBPORT}/${WOLWEBVDIR}/health`

### PR DESCRIPTION
**Pull request by ellisdickinson46**
Fixes #40 
Update health check to honour customised virtual directories

### CODE REVIEW

**Comment by sameerdhoot** [comment]
Hi @ellisdickinson46 Thank you submitting this PR. Did you actually test this? I don't recall if ${WOLWEBVDIR} is defined. Sorry if it is. I might have forgotten about this.

**Comment by sameerdhoot** [comment]
Hi @ellisdickinson46 Thank you submitting this PR. Did you actually test this? I dont recall if ${WOLWEBVDIR} is defined. Sorry if it is. I might have forgotten about this.

**Comment by ellisdickinson46** [comment]
In my docker testing, this fix does appear to function as expected by simply changing the health check address, however I have also added some default values to the docker file anyways to ensure more predictable behaviour moving forward.

**Comment by ellisdickinson46** [comment]
Virtual directory options have been present in config.json from initial commits from what I gather. Without defining it as an argument WOLWEBVDIR, the end user would have to define this to ensure the container health check works correctly, hence I have added the relevant argument lines.

**Pull request merged**
