### PR TITLE
Cleaned up paths if pages.go and wolweb.js

### PR DESCRIPTION
**Pull request by Bleialf**
Without those changes i would get "Error: Problem with getting approver information"

### CODE REVIEW

**Comment by Bleialf** [comment]
My error sorry. Didn't actually want to add the changes to the Dockerfile/config.json. But did you delete it from your repo altogether now?

**Comment by Bleialf** [comment]
To be completely honest, i didn't know that changes to my fork would be included in the pullrequest after submitting the pr xD. The changes to the Dockerfile happened after i submitted the pr. Sry once again.

**Comment by sameerdhoot** [comment]
> My error sorry. Didn't actually want to add the changes to the Dockerfile/config.json. But did you delete it from your repo altogether now?

Oops!! I made a mistake as well by deleting the Dockerfile from my repo as well. I have restored the file along with config.json file

**Comment by sameerdhoot** [comment]
> To be completely honest, i didn't know that changes to my fork would be included in the pullrequest after submitting the pr xD. The changes to the Dockerfile happened after i submitted the pr. Sry once again.

Never mind. We all learn. Thank you for the PR though.

**Pull request merged**
